  Pour 1 1/2 cups warm water into a large bowl; sprinkle with yeast and let stand until foamy, about 5 minutes. Advertisement
Whisk sugar, oil, and salt into yeast mixture. Add flour and stir until a sticky dough forms. Transfer dough to an oiled bowl and brush top with oil. ...
Dough can be stored in an oiled bowl, covered with plastic, in refrigerator up to 2 hours. ...
